### ISSUE TITLE
Some contracts not available using findById

### ISSUE THREAD

**Issue by nickjevershed** [austender/austender-ocds-api#2]
A couple of examples:

https://api.tenders.gov.au/ocds/findById/CN192806

https://www.tenders.gov.au/Cn/Show/cd0542e2-0ed6-3ffd-6fe5-797c0d9e81e0

https://api.tenders.gov.au/ocds/findById/CN303127

https://www.tenders.gov.au/Cn/Show/8cbc13d9-9c42-90f6-ac75-c0ba3f0cdb34

**Comment by TanyaChavdarova** [comment]
The scope here appears to be rather large.

During a bulk test of the [findByDates/contractLastModified](https://app.swaggerhub.com/apis/austender/ocds-api/1.1#/default/findByDates) endpoint (for the date range of January 2010 to March 2022), we compared the contract notice IDs with those from the "[Contract Notice and Amendments Published Criteria](https://www.tenders.gov.au/Reports/CnAndAmendmentsForm)" reports for the same period.
There were more than 200,000 contract notice entries (parents or amendments) that were NOT present in the API response (but were found in the up-to-date report files).

We then queried the [findById](https://app.swaggerhub.com/apis/austender/ocds-api/1.1#/default/findById) API endpoint for each of those and got a `{"errorCode": 100, "message": "No Records found having CNID: …"}` response for 99% of them. We received successful responses only for 2110 contract notice entries.

The full list of missing contract notice IDs is attached ([missing_contract_notice_ids_2010_2022.csv](https://github.com/austender/austender-ocds-api/files/8370293/missing_contract_notice_ids_2010_2022.csv)).

A closer look reveals that most of these contracts are fully unavailable in the API i.e. there are neither parent, nor amendment entries accessible through the API for these CN IDs. (A peculiar exception appear to be 465 CN IDs which do have some, but not all, of their records accessible through the endpoints - attached [existing_cn_ids_with_missing_amendments_2010_2022.csv](https://github.com/austender/austender-ocds-api/files/8370296/existing_cn_ids_with_missing_amendments_2010_2022.csv))

Half of the missing contract notice entries are from the "Department of Defence" agency (106,501) and most of them were published in the period of 2010-2012.

**Comment by andrewlorien** [comment]
We believe this is fixed.
The problem was related to particular amendments across year boundaries not being indexed properly.  That is now fixed.
However:
A decision was made **not to include contracts published or amended prior to 1 Jan 2013** in the OCDS feed.  We'll make that clear in the documentation on this repo.
