### ISSUE TITLE
502 internal server error on specific page

### ISSUE THREAD

**Issue by pl4nty** [austender/austender-ocds-api#20]
[This page](https://api.tenders.gov.au/ocds/findByDates/contractStart/2021-01-01T00:00:00Z/2022-01-01T00:00:00Z?cursor=Vci-e_AwQW9ONGhjSGhpZFVDTEVOT016TTBOekUzT1MxQk1TeERUak16TkRjeE56a3RRVEU9sN4F&prevcursor=VckIp8wwQW9OdzhNYmYyT29DTEVOT016ZzBOREV4TmkxQk1peERUak00TkRReE1UWXRRVEk9zN0F&lastcursor=initial) returns a 502, and prevents further pagination since it's cursor-based

**Comment by andrewlorien** [comment]
This was a problem with amendments to Contract Notices which were in draft status (ie not published to the public, with no permission to view their details) being included in the search results.  The search results have been amended so they no longer include those records, and the query no longer returns a 502.

Thanks for pointing it out.
