### ISSUE TITLE
API not working since 12 May 2021

### ISSUE THREAD

**Issue by naverone** [austender/austender-ocds-api#5]
API calls using dates or CN ids return errors after 12 May.

**Comment by saetukuru** [comment]
Upvoting this, the API returns no data from 13th May.

**Comment by austender** [comment]
We apologise for the occasional missing updates to the OCDS data, and for the very long pause in us reponding to these issues.  We've improved our monitoring of the function that creates that data this week.  And also started monitoring this repo better.
